version: '3.7'

networks:
  application-kafka:
    driver: bridge
    name: application-kafka
    external: true
  application-services:
    driver: bridge
    name: application-services
    external: true